"""name of the migration

Revision ID: 0238b73d30ee
Revises: fc191e2d1d6c
Create Date: 2025-08-30 19:09:28.109578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0238b73d30ee'
down_revision: Union[str, None] = 'fc191e2d1d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_accounts', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('sub_accounts', 'password_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_accounts', sa.Column('password_encrypted', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sub_accounts', 'password')
    # ### end Alembic commands ###
