"""first new migration

Revision ID: 2731f948b63d
Revises: 
Create Date: 2025-05-28 23:33:12.085485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2731f948b63d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_users',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('IdKeycloak', sa.UUID(), nullable=False),
    sa.Column('HashMasterPassword', sa.String(), nullable=False),
    sa.Column('SaltArgon', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('IdKeycloak')
    )
    op.create_table('Subaccounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_encrypted', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['local_users.Id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subaccounts')
    op.drop_table('local_users')
    # ### end Alembic commands ###
