"""replace rsa keys with ec/pq hybrid keys and salt

Revision ID: 300f44a4afd8
Revises: ed346256cc9e
Create Date: 2026-08-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300f44a4afd8'
down_revision: Union[str, None] = 'ed346256cc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'private_key')
    op.drop_column('users', 'public_key')
    op.add_column('users', sa.Column('salt', sa.String(), nullable=False))
    op.add_column('users', sa.Column('public_key_ec', sa.LargeBinary(), nullable=False))
    op.add_column('users', sa.Column('private_key_ec', sa.LargeBinary(), nullable=False))
    op.add_column('users', sa.Column('public_key_pq', sa.LargeBinary(), nullable=False))
    op.add_column('users', sa.Column('private_key_pq', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'private_key_pq')
    op.drop_column('users', 'public_key_pq')
    op.drop_column('users', 'private_key_ec')
    op.drop_column('users', 'public_key_ec')
    op.drop_column('users', 'salt')
    op.add_column('users', sa.Column('public_key', sa.String(), nullable=False))
    op.add_column('users', sa.Column('private_key', sa.String(), nullable=False))
    # ### end Alembic commands ###
