"""project restructuring

Revision ID: 53595b177bc7
Revises: fbcd91f22b65
Create Date: 2026-01-16 16:42:10.193739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53595b177bc7'
down_revision: Union[str, None] = 'fbcd91f22b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_accounts')
    op.drop_table('local_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_users',
    sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('IdKeycloak', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('SaltArgon', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='local_users_pkey'),
    sa.UniqueConstraint('IdKeycloak', name='local_users_IdKeycloak_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('sub_accounts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['local_users.Id'], name='sub_accounts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sub_accounts_pkey')
    )
    # ### end Alembic commands ###
