"""Recreation of the user table for the data of the password encription

Revision ID: aaefd5cac860
Revises: 1611de286833
Create Date: 2025-05-16 16:43:39.415514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaefd5cac860'
down_revision: Union[str, None] = '1611de286833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('salt', sa.String(length=100), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'salt')
    op.drop_column('users', 'hash')
    # ### end Alembic commands ###
