"""add username and code to users

Revision ID: ed346256cc9e
Revises: ad21ab646e3f
Create Date: 2026-08-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed346256cc9e'
down_revision: Union[str, None] = 'ad21ab646e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('code', sa.String(length=10), nullable=False))
    op.create_unique_constraint('uq_users_username_code', 'users', ['username', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_username_code', 'users', type_='unique')
    op.drop_column('users', 'code')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
