"""removal of hash

Revision ID: fbcd91f22b65
Revises: 0238b73d30ee
Create Date: 2025-08-30 20:34:19.544675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcd91f22b65'
down_revision: Union[str, None] = '0238b73d30ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_users', 'HashMasterPassword')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_users', sa.Column('HashMasterPassword', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
