"""table relations improovement

Revision ID: fc191e2d1d6c
Revises: 4c414db4b21b
Create Date: 2025-06-02 16:23:58.118290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc191e2d1d6c'
down_revision: Union[str, None] = '4c414db4b21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sub_accounts_user_id_fkey', 'sub_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'sub_accounts', 'local_users', ['user_id'], ['Id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_accounts', type_='foreignkey')
    op.create_foreign_key('sub_accounts_user_id_fkey', 'sub_accounts', 'local_users', ['user_id'], ['Id'])
    # ### end Alembic commands ###
