name: Docker Compose Python CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose up -d
          sleep 10  # Attendi che i container siano pronti

      - name: Verifica container attivi
        run: docker ps -a

      - name: Esegui i test (opzionale)
        run: docker exec password_manager_api pytest  # se usi pytest
